inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5

Rails/SaveBang:
  AllowedReceivers:
    - Elasticsearch::Model.client.indices
