inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config.ru
    - db/schema.rb
    - vendor/**/*
    - vendor/bundle/**/*

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'

Style/FormatStringToken:
  Exclude:
    - "config/routes.rb"

Rails/OutputSafety:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: slashes

Rails/SaveBang:
  AllowedReceivers:
    - Elasticsearch::Model.client.indices
