---
applications:
- name: find-data-beta
  instances: 4
  memory: 512M
  buildpack: https://github.com/cloudfoundry/ruby-buildpack.git#v1.8.17
  stack: cflinuxfs3
  routes:
  - route: find-data-beta.cloudapps.digital
  - route: data.gov.uk
  env:
    RAILS_ENV: production
    RACK_ENV: production
    CKAN_DOMAIN: ckan.publishing.service.gov.uk
    GOVUK_APP_DOMAIN: www.gov.uk
    GOVUK_WEBSITE_ROOT: https://www.gov.uk
  services:
  - find-production-secrets
  - elasticsearch-7-production
  - logit-ssl-drain
