---
applications:
- name: find-data-beta
  instances: 8
  memory: 256M
  buildpack: https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.14
  routes:
  - route: find-data-beta.cloudapps.digital
  - route: beta.data.gov.uk
  - route: data.gov.uk
  env:
    RAILS_ENV: production
    RACK_ENV: production
  services:
  - find-production-secrets
  - logit-ssl-drain
  - beta-production-elasticsearch
  - dgu-prometheus
