---
applications:
- name: find-data-beta
  instances: 4
  memory: 512M
  buildpack: https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.16
  routes:
  - route: find-data-beta.cloudapps.digital
  - route: data.gov.uk
  env:
    RAILS_ENV: production
    RACK_ENV: production
  services:
  - find-production-secrets
  - logit-ssl-drain
  - beta-production-elasticsearch
