module Collections
  COLLECTIONS = {
    "business-and-economy": [
      { "title": "UK trade", "slug": "uk-trade" },
      { "title": "Bank of England interest rates", "slug": "bank-of-england-interest-rates" },
      { "title": "Inflation", "slug": "inflation" },
      { "title": "Get company information", "slug": "get-company-information" },
      { "title": "Get charity information", "slug": "get-charity-information" },
      { "title": "Food hygiene ratings", "slug": "food-hygiene-ratings" },
      { "title": "Fuel and oil prices", "slug": "fuel-and-oil-prices" },
      { "title": "Agricultural commodity prices", "slug": "agricultural-commodity-prices" },
      { "title": "Energy prices", "slug": "energy-prices" },
      { "title": "Electricity", "slug": "electricity" },
    ],
    "environment": [
      { "title": "Weather", "slug": "weather" },
      { "title": "Air quality", "slug": "air-quality" },
      { "title": "Long-term flood risk", "slug": "long-term-flood-risk" },
      { "title": "Flood alerts", "slug": "flood-alerts" },
      { "title": "Water quality", "slug": "water-quality" },
      { "title": "Fish and ecology", "slug": "fish-and-ecology" },
      { "title": "Public registers", "slug": "public-registers" },
      { "title": "LIDAR", "slug": "lidar" },
      { "title": "Aerial photography", "slug": "aerial-photography" },
      { "title": "Storm overflows", "slug": "storm-overflows" },
      { "title": "Landfill sites", "slug": "landfill-sites" },
      { "title": "Road noise", "slug": "road-noise" },
      { "title": "Rail noise", "slug": "rail-noise" },
      { "title": "Main rivers", "slug": "main-rivers" },
      { "title": "Coastal erosion", "slug": "coastal-erosion" },
      { "title": "Climate projections", "slug": "climate-projections" },
      { "title": "Forest and woodlands", "slug": "forest-and-woodlands" },
      { "title": "Non-woodland trees", "slug": "non-woodland-trees" },
      { "title": "Sites of Special Scientific Interest", "slug": "sites-of-special-scientific-interest" },
    ],
    "government": [
      { "title": "Election results data", "slug": "election-results-data" },
      { "title": "Service assessment reports", "slug": "service-assessment-reports" },
      { "title": "Local government finance", "slug": "local-government-finance" },
      { "title": "Council Tax statistics", "slug": "council-tax-statistics" },
      { "title": "Contracts finder", "slug": "contracts-finder" },
      { "title": "Transparency data", "slug": "transparency-data" },
    ],
    "land-and-property": [
      { "title": "UK house prices", "slug": "uk-house-prices" },
      { "title": "Property price paid", "slug": "property-price-paid" },
      { "title": "Land and property ownership", "slug": "land-and-property-ownership" },
      { "title": "Planning data", "slug": "planning-data" },
      { "title": "Addresses", "slug": "addresses" },
      { "title": "Dwelling stock (including vacancies)", "slug": "dwelling-stock" },
      { "title": "Rents, lettings and tenancies", "slug": "rents-lettings-and-tenancies" },
      { "title": "English Housing Survey", "slug": "english-housing-survey" },
      { "title": "Housing supply", "slug": "housing-supply" },
      { "title": "Energy performance of buildings", "slug": "energy-performance-of-buildings" },
      { "title": "Fire statistics", "slug": "fire-statistics" },
    ],
    "people": [
      { "title": "Births", "slug": "births" },
      { "title": "Deaths", "slug": "deaths" },
      { "title": "Public health dashboard", "slug": "public-health-dashboard" },
      { "title": "Population estimates", "slug": "population-estimates" },
      { "title": "Immigration", "slug": "immigration" },
      { "title": "Social mobility", "slug": "social-mobility" },
      { "title": "Deprivation", "slug": "deprivation" },
      { "title": "Homelessness", "slug": "homelessness" },
      { "title": "Police recorded crime and outcomes", "slug": "police-recorded-crime-and-outcomes" },
      { "title": "Courts management", "slug": "courts-management" },
      { "title": "Early years and childcare inspections and outcomes", "slug": "early-years-and-childcare-inspections-and-outcomes" },
      { "title": "State-funded schools inspections and outcomes", "slug": "state-funded-schools-inspections-and-outcomes" },
      { "title": "Pupil attendance", "slug": "pupil-attendance" },
      { "title": "Compare school performance", "slug": "compare-school-performance" },
      { "title": "Vocational qualifications", "slug": "vocational-qualifications" },
      { "title": "Museum and gallery visits", "slug": "museum-and-gallery-visits" },
      { "title": "Family food statistics", "slug": "family-food-statistics" },
    ],
    "transport": [
      { "title": "Road traffic", "slug": "road-traffic" },
      { "title": "Road safety", "slug": "road-safety" },
      { "title": "Road conditions", "slug": "road-conditions" },
      { "title": "Real-time and historic train information", "slug": "real-time-and-historic-train-information" },
      { "title": "Bus statistics", "slug": "bus-statistics" },
      { "title": "MOT test results", "slug": "mot-results" },
      { "title": "Driving tests", "slug": "driving-tests" },
      { "title": "Fishing vessels", "slug": "fishing-vessels" },
      { "title": "National Travel Survey", "slug": "national-travel-survey" },
      { "title": "Transport connectivity", "slug": "transport-connectivity" },
      { "title": "Maritime and shipping", "slug": "maritime-and-shipping" },
    ],
  }.freeze
end
