# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10f333040a501425f43bc0c293cf3d8e38bfc719e57c65216b79caf499acc5e8f5fef645631e50b57bae568d1798e6557c5af9512bdeca8ea8b59a515a1b9a19

test:
  secret_key_base: 8d6cf7740416e40b2736c6f9ff87f1497cbc562e40ca8122365c8681334caecc838443461667c169a14a2a6fea94d29f991d3e64d9e29597065358914f86bc99

# Do not keep integration, staging or production secrets in the unencrypted
# secrets file. Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets and move the
# `integration:`, `staging:` and `production:` environments over there.

integration:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
