name: Build and push DGU Find Image on tags

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_push:
    name: Build and push the DGU Find Image w/ tags
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-image.yaml
    with:
      buildType: build_push_with_gittag
      gitRef: ${{ github.ref_name }}
