name: Update charts PR

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build and push multi-arch images" ]
    types:
      - completed
    branches:
      - main-mvp

jobs:
  update_charts:
    name: Update Find SHA in charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout datagovuk_find repository
        uses: actions/checkout@v4
        with:
          repository: alphagov/datagovuk_find
      - name: Update Find SHA in govuk-dgu-charts
        run: bash ./docker/update-find-sha-mvp.sh
        env:
          GH_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
          GH_REF: ${{ github.ref_name }}
          IS_TAG: "false"
          ENVS: "integration"
