name: Create charts PR on tags creation

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build and push images on tags" ]
    types:
      - completed

jobs:
  create_pr:
    name: Create charts PR on tags creation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set GH_REF
        run: echo "GH_REF=`echo $(git fetch -t -q | sort --version-sort | tail -n1)`" >> $GITHUB_ENV
      - run: bash ./docker/create-pr.sh
        env:
          GH_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
          IS_TAG: "true"
          ENVS: "staging,production"
