on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  render-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.10'
      - name: Install ruby dependencies
        run: bundle install
      - name: Run markdown:render task
        run: bundle exec rake markdown:render